/**
 * Saints directory seed (D-025). Biographies are short, original summaries written for Ecclesios
 * (not copied from any book or website), so they can stay in production and be expanded later.
 * Ranks follow the General Roman Calendar.
 */
import type { CelebrationRank } from "@ecclesios/shared/domain";

export interface SeedSaint {
  name: string;
  title: string | null;
  feast: [month: number, day: number];
  rank: CelebrationRank;
  summary: string;
  patronage: string[];
  born: string | null;
  died: string | null;
  biography: string[];
}

const S = (
  name: string,
  title: string | null,
  feast: [number, number],
  rank: CelebrationRank,
  summary: string,
  patronage: string[],
  born: string | null,
  died: string | null,
  biography: string[],
): SeedSaint => ({ name, title, feast, rank, summary, patronage, born, died, biography });

export const SEED_SAINTS: SeedSaint[] = [
  S("Thomas Aquinas", "Priest and Doctor of the Church", [1, 28], "MEMORIAL",
    "Dominican friar whose writings joined faith and reason.",
    ["Students", "Catholic schools", "Theologians"], "c. 1225", "1274",
    ["Born into a noble family near Aquino in Italy, Thomas joined the new Order of Preachers against his family's wishes.",
     "He taught in Paris and Italy, and his Summa Theologiae became one of the most influential works of Christian thought. He showed how reason and faith work together in seeking the truth about God."]),
  S("Anthony of Egypt", "Abbot", [1, 17], "MEMORIAL",
    "Desert hermit and a father of Christian monastic life.",
    ["Monks", "Farmers", "Butchers"], "c. 251", "356",
    ["After hearing the Gospel call to sell everything and follow Christ, Anthony gave away his inheritance and withdrew into the Egyptian desert.",
     "Many came to learn from him, and the communities that formed around him helped shape monastic life in the Church."]),
  S("Josephine Bakhita", "Virgin", [2, 8], "OPTIONAL_MEMORIAL",
    "Sudanese woman freed from slavery who became a Canossian Sister.",
    ["Sudan", "Victims of human trafficking"], "c. 1869", "1947",
    ["Kidnapped as a child in Darfur and sold into slavery several times, Bakhita was later taken to Italy, where she came to know Christ and won her freedom.",
     "She entered the Canossian Daughters of Charity and became known for her gentleness and joy. She was canonised in 2000."]),
  S("Perpetua and Felicity", "Martyrs", [3, 7], "MEMORIAL",
    "Young mothers martyred together in Carthage, North Africa.",
    ["Mothers", "Expectant mothers"], null, "203",
    ["Perpetua, a young noblewoman, and Felicity, an enslaved woman, were catechumens in Carthage when they were arrested for their faith.",
     "They were baptised in prison and died together in the arena. The account of their imprisonment is one of the oldest Christian writings by a woman."]),
  S("Patrick", "Bishop", [3, 17], "OPTIONAL_MEMORIAL",
    "Missionary bishop who brought the Gospel to Ireland.",
    ["Ireland", "Engineers"], "c. 385", "c. 461",
    ["Taken from Britain to Ireland as a young captive, Patrick escaped after several years but later felt called to return.",
     "As a bishop he preached throughout Ireland, founded churches and helped form a lasting Christian culture there."]),
  S("Joseph", "Spouse of the Blessed Virgin Mary", [3, 19], "SOLEMNITY",
    "Husband of Mary and guardian of the child Jesus.",
    ["The universal Church", "Fathers", "Workers", "A happy death"], null, null,
    ["Joseph, a carpenter of Nazareth from the house of David, received Mary as his wife and cared for Jesus as his own son.",
     "The Gospels show him as a just and faithful man who listened to God and acted. He is honoured as patron of the universal Church."]),
  S("Catherine of Siena", "Virgin and Doctor of the Church", [4, 29], "MEMORIAL",
    "Dominican tertiary, mystic and peacemaker.",
    ["Europe", "Italy", "Nurses"], "1347", "1380",
    ["Catherine lived a life of prayer and service to the sick and poor in Siena as a lay member of the Dominican family.",
     "She wrote letters to popes and rulers urging peace and reform, and encouraged the return of the papacy from Avignon to Rome."]),
  S("Athanasius", "Bishop and Doctor of the Church", [5, 2], "MEMORIAL",
    "Bishop of Alexandria who defended the divinity of Christ.",
    ["Theologians"], "c. 296", "373",
    ["As bishop of Alexandria in Egypt, Athanasius held firmly to the faith of the Council of Nicaea that the Son is truly God.",
     "He was exiled several times for this, yet his teaching and writings helped the whole Church keep the faith of Nicaea."]),
  S("Charles Lwanga and Companions", "Martyrs", [6, 3], "MEMORIAL",
    "Ugandan martyrs who died for Christ in 1885–1887.",
    ["Uganda", "African youth", "Catholic Action"], null, "1886",
    ["Charles Lwanga served at the court of the king of Buganda and instructed the young pages in the faith.",
     "When the king turned against the Christians, Charles and many companions, Catholic and Anglican, chose death rather than deny Christ. They were canonised in 1964."]),
  S("Anthony of Padua", "Priest and Doctor of the Church", [6, 13], "MEMORIAL",
    "Franciscan preacher known for his teaching and care of the poor.",
    ["Lost things", "The poor", "Travellers"], "c. 1195", "1231",
    ["Born in Lisbon, Anthony joined the Franciscans hoping to serve as a missionary.",
     "He became a celebrated preacher in Italy and France, admired for his knowledge of Scripture and his love for the poor."]),
  S("Peter and Paul", "Apostles", [6, 29], "SOLEMNITY",
    "The two great apostles of Rome.",
    ["Rome", "The Church"], null, "c. 64–67",
    ["Peter, the fisherman whom Jesus made the rock of the Church, and Paul, the persecutor who became the Apostle to the Gentiles, both gave their lives in Rome.",
     "The Church celebrates them together as the pillars of its faith and mission."]),
  S("Benedict", "Abbot", [7, 11], "MEMORIAL",
    "Father of Western monasticism and author of the Rule.",
    ["Europe", "Monks", "Students"], "c. 480", "c. 547",
    ["Benedict left his studies in Rome to seek God in solitude and later founded monasteries, including Monte Cassino.",
     "His Rule, centred on prayer and work, has guided monastic communities for fifteen centuries."]),
  S("Mary Magdalene", null, [7, 22], "FEAST",
    "Disciple of Jesus and first witness of the Resurrection.",
    ["Converts", "Women"], null, null,
    ["Mary of Magdala followed Jesus in Galilee, stood by the cross and went to the tomb on Easter morning.",
     "The risen Lord sent her to announce the Resurrection to the apostles, and she is honoured as the apostle to the apostles."]),
  S("Ignatius of Loyola", "Priest", [7, 31], "MEMORIAL",
    "Founder of the Society of Jesus and author of the Spiritual Exercises.",
    ["Retreats", "Soldiers"], "1491", "1556",
    ["A Basque soldier wounded in battle, Ignatius turned to God while recovering and began a deep spiritual journey.",
     "With his companions he founded the Society of Jesus, devoted to education, mission and helping souls."]),
  S("Clare", "Virgin", [8, 11], "MEMORIAL",
    "Follower of Saint Francis and founder of the Poor Clares.",
    ["Television", "Embroiderers"], "1194", "1253",
    ["Inspired by Francis of Assisi, Clare left her family to live in poverty and prayer.",
     "She founded the Order of Poor Ladies at San Damiano and led the community for over forty years."]),
  S("Monica", null, [8, 27], "MEMORIAL",
    "Mother of Saint Augustine, known for her persevering prayer.",
    ["Mothers", "Wives"], "c. 331", "387",
    ["Monica, born in North Africa, prayed for many years for the conversion of her son Augustine.",
     "She lived to see his baptism in Milan and died soon after at Ostia, on the way home to Africa."]),
  S("Augustine", "Bishop and Doctor of the Church", [8, 28], "MEMORIAL",
    "Bishop of Hippo whose Confessions tell of his conversion.",
    ["Theologians", "Printers", "Brewers"], "354", "430",
    ["Born in Thagaste in North Africa, Augustine searched for truth through philosophy before turning to Christ in Milan.",
     "As bishop of Hippo he preached, wrote and served his people for over thirty years. His writings shaped Christian theology in the West."]),
  S("Cornelius and Cyprian", "Martyrs", [9, 16], "MEMORIAL",
    "A pope and an African bishop who stood together in a time of persecution.",
    ["North Africa"], null, "253 and 258",
    ["Cornelius was bishop of Rome and Cyprian bishop of Carthage at a time of persecution and division.",
     "Cyprian defended Cornelius's election, and both gave their lives for Christ. Cyprian's writings on the unity of the Church are still read today."]),
  S("Vincent de Paul", "Priest", [9, 27], "MEMORIAL",
    "Apostle of charity who founded communities to serve the poor.",
    ["Charitable societies", "The poor"], "1581", "1660",
    ["A French priest, Vincent devoted his life to the poor, the sick and prisoners.",
     "He founded the Congregation of the Mission and, with Louise de Marillac, the Daughters of Charity. Many parish charitable societies bear his name."]),
  S("Michael, Gabriel and Raphael", "Archangels", [9, 29], "FEAST",
    "The archangels named in Scripture.",
    ["Police and soldiers (Michael)", "Messengers (Gabriel)", "Healers and travellers (Raphael)"], null, null,
    ["Scripture names three archangels: Michael, who defends God's people; Gabriel, who announced the birth of John the Baptist and of Jesus; and Raphael, who guided Tobias.",
     "The Church honours them together as messengers of God's care."]),
  S("Jerome", "Priest and Doctor of the Church", [9, 30], "MEMORIAL",
    "Scholar who translated the Bible into Latin.",
    ["Biblical scholars", "Translators", "Librarians"], "c. 342", "420",
    ["Jerome studied in Rome and lived as a monk in Bethlehem, devoting his life to Scripture.",
     "His Latin translation, the Vulgate, became the Bible of the Western Church for over a thousand years."]),
  S("Thérèse of the Child Jesus", "Virgin and Doctor of the Church", [10, 1], "MEMORIAL",
    "Carmelite nun of Lisieux who taught the 'little way' of trust and love.",
    ["Missions", "Missionaries", "Florists"], "1873", "1897",
    ["Thérèse entered the Carmel of Lisieux at fifteen and died there at twenty-four.",
     "Her autobiography, Story of a Soul, describes a 'little way' of doing small things with great love. Though she never left her convent, she is patron of the missions."]),
  S("Francis of Assisi", null, [10, 4], "MEMORIAL",
    "Founder of the Franciscans who embraced poverty and loved all creation.",
    ["Ecology", "Animals", "Italy"], "c. 1181", "1226",
    ["The son of a wealthy merchant, Francis gave up his inheritance to live the Gospel in poverty.",
     "His brothers spread across Europe preaching peace and penance, and his Canticle of the Creatures praises God through all he has made."]),
  S("Faustina Kowalska", "Virgin", [10, 5], "OPTIONAL_MEMORIAL",
    "Polish sister through whom devotion to Divine Mercy spread.",
    ["Divine Mercy devotion"], "1905", "1938",
    ["Helena Kowalska joined the Congregation of the Sisters of Our Lady of Mercy, taking the name Maria Faustina.",
     "Her diary records her experiences of Christ's mercy. She was canonised in 2000, when Divine Mercy Sunday was established."]),
  S("Bruno", "Priest", [10, 6], "OPTIONAL_MEMORIAL",
    "Founder of the Carthusian order.",
    ["Carthusians"], "c. 1030", "1101",
    ["Bruno was a respected teacher in Reims before leaving to seek God in solitude.",
     "With companions he founded the first Carthusian community in the mountains near Grenoble."]),
  S("John XXIII", "Pope", [10, 11], "OPTIONAL_MEMORIAL",
    "Pope who opened the Second Vatican Council.",
    ["Papal delegates"], "1881", "1963",
    ["Angelo Roncalli, from a farming family near Bergamo, served as a diplomat for the Holy See before becoming Patriarch of Venice.",
     "Elected pope in 1958, he called the Second Vatican Council. He was canonised in 2014."]),
  S("Teresa of Jesus", "Virgin and Doctor of the Church", [10, 15], "MEMORIAL",
    "Carmelite reformer and teacher of prayer, also called Teresa of Ávila.",
    ["Spain", "People in religious orders"], "1515", "1582",
    ["Teresa entered the Carmelite convent in Ávila and, after years of struggle in prayer, received a deep experience of God.",
     "She reformed the Carmelite order with Saint John of the Cross, and her writings, such as The Interior Castle, remain guides to prayer."]),
  S("Ignatius of Antioch", "Bishop and Martyr", [10, 17], "MEMORIAL",
    "Early bishop whose letters witness to the faith of the first Christians.",
    ["The Church in the Eastern Mediterranean"], null, "c. 107",
    ["Ignatius was bishop of Antioch, where the disciples were first called Christians.",
     "Taken to Rome to be martyred, he wrote letters to the churches on the way, speaking of the Eucharist, the bishop and unity in Christ."]),
  S("Luke", "Evangelist", [10, 18], "FEAST",
    "Author of the Gospel of Luke and the Acts of the Apostles.",
    ["Physicians", "Artists"], null, null,
    ["Luke, a companion of Saint Paul described as a physician, wrote a Gospel that highlights God's mercy and care for the poor.",
     "His second book, the Acts of the Apostles, tells how the Gospel spread from Jerusalem to Rome."]),
  S("John Paul II", "Pope", [10, 22], "OPTIONAL_MEMORIAL",
    "Polish pope who travelled the world and called young people to Christ.",
    ["World Youth Day", "Families"], "1920", "2005",
    ["Karol Wojtyła lived through occupation in Poland, was ordained in secret and later became archbishop of Kraków.",
     "Pope from 1978 to 2005, he visited more than a hundred countries, including Ghana, and began World Youth Day. He was canonised in 2014."]),
  S("Simon and Jude", "Apostles", [10, 28], "FEAST",
    "Two of the Twelve, honoured together.",
    ["Desperate causes (Jude)"], null, null,
    ["Simon, called the Zealot, and Jude, also called Thaddeus, were among the twelve apostles chosen by Jesus.",
     "Tradition says they preached the Gospel together and gave their lives for Christ."]),
  S("Martin de Porres", "Religious", [11, 3], "OPTIONAL_MEMORIAL",
    "Dominican brother of Lima known for his humility and care of the sick.",
    ["Racial harmony", "Social justice", "Barbers"], "1579", "1639",
    ["Born in Lima to a Spanish father and a mother of African descent, Martin faced prejudice from childhood.",
     "As a Dominican brother he cared for the sick and poor of every background, and was known for his humility and kindness."]),
  S("Cecilia", "Virgin and Martyr", [11, 22], "MEMORIAL",
    "Roman martyr and patron of church music.",
    ["Musicians", "Church choirs"], null, null,
    ["Cecilia is one of the most honoured martyrs of the early Roman Church, remembered in the Roman Canon of the Mass.",
     "Tradition associates her with music, and choirs around the world take her as their patron."]),
  S("Francis Xavier", "Priest", [12, 3], "MEMORIAL",
    "Jesuit missionary who preached in India, Southeast Asia and Japan.",
    ["Missions", "Missionaries"], "1506", "1552",
    ["One of the first companions of Ignatius of Loyola, Francis Xavier sailed to Asia as a missionary.",
     "He preached in India, the Malay world and Japan, and died while hoping to enter China. With Thérèse of Lisieux he is patron of the missions."]),
  S("Stephen", "First Martyr", [12, 26], "FEAST",
    "Deacon and the first to die for Christ.",
    ["Deacons"], null, "c. 34",
    ["Stephen was one of the seven chosen by the apostles to serve the community in Jerusalem.",
     "Accused before the council, he bore witness to Christ and was stoned to death, praying for those who killed him."]),
];
